C# UDPipe Bindings
==================

Installation
============

Binary C# bindings are available in UDPipe binary packages.

To compile C# bindings manually, run make in the bindings/csharp directory,
optionally with the options descriged in UDPipe Installation.


C# Bindings API
===============

UDPipe library bindings is available in the Ufal.UDPipe namespace.

The bindings is a straightforward conversion of the C++ bindings API. The
bindings requires native C++ library libudpipe_csharp (called udpipe_csharp on
Windows).


C++ Bindings API
================


Helper Structures
-----------------


Main Classes
------------
